export enum Block {
  AddUserName = 'add_user_name_block',
  AddUserEmailAddress = 'add_user_email_block',
  AddUserMobileNumber = 'add_user_mobile_num_block',
  SelectUserRole = 'select_user_role_block',
  GetSlackInviteLink = 'get_slack_invite_link_block',
  GetJobRoleName = 'get_jobrole_name_block',
  GetNoofChannels = 'get_no_of_channels_block',
  SelectChannelType = 'select_channel_type_block',
  GetPublicChannelNames = 'get_public_channel_names_block',
  GetPrivateChannelNames = 'get_private_channel_names_block',
  SelectJobRole = 'select_job_role_block',
  GetProjectName = 'get_project_name_block',
  SelectProjectChannelRequired = 'select_projectchannel_required_block',
  SelectGlobalChannelMembers = 'select_global_channel_members_block',
}
